server:
  port: 8079

spring:
  application:
    name: Apigateway
  cloud:
    gateway:
      routes:
        - id: users-microservice
          uri: lb://users-microservice
          predicates:
            - Path=/api/users/**
          filters:
            - name: jwtAuthenticationFilter
              args:
                publicEndpoints:
                  - path: /api/auth/login
                    methods: [POST]
                  - path: /api/auth/register
                    methods: [POST]

        - id: productors-microservice
          uri: lb://productors-microservice
          predicates:
            - Path=/api/productors/**
          filters:
            - name: jwtAuthenticationFilter

        - id: products-microservice
          uri: lb://products-microservice
          predicates:
            - Path=/api/products/**
          filters:
            - name: jwtAuthenticationFilter
              args:
                publicEndpoints:
                  - path: /api/products/**
                    methods: [GET]
        - id: sales-microservice
          uri: lb://sales-microservice
          predicates:
            - Path=/api/sales/**
          filters:
            - name: jwtAuthenticationFilter
