spring:
  application:
    name: Apigateway
  cloud:
    gateway:
      routes:
        - id: users-microservice
          uri: lb://users-microservice
          predicates:
            - Path=/api/usuarios/**
          filters:
            - name: jwtAuthenticationFilter
              args:
                publicEndpoints:
                  - path: /api/usuarios/registro
                    methods: [POST]
                  - path: /api/usuarios/login
                    methods: [POST]
        - id: purchases-microservice
          uri: lb://purchases-microservice     
          predicates:
              - Path=/api/compras/**,/api/envios/**
          filters:
            - name: jwtAuthenticationFilter    
        - id: productors-microservice
          uri: lb://productors-microservice
          predicates:
            - Path=/api/productores/**,/api/gremios/**
          filters:
            - name: jwtAuthenticationFilter
              args:
                publicEndpoints:
                  - path: /api/productores/**
                    methods: [GET]
                  - path: /api/gremios/**
                    methods: [GET]                    
        - id: products-microservice
          uri: lb://products-microservice
          predicates:
            - Path=/api/productos/**
          filters:
            - name: jwtAuthenticationFilter
              args:
                publicEndpoints:
                  - path: /api/productos/**
                    methods: [GET]
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173,https://agromercadolocal.vercel.app"
            allowedMethods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
