spring:
  application:
    name: Apigateway
  cloud:
    gateway:
      routes:
        - id: users-microservice
          uri: lb://users-microservice
          predicates:
            - Path=/api/usuarios/**
          filters:
            - name: jwtAuthenticationFilter
              args:
                publicEndpoints:
                  - path: /api/usuarios/registro
                    methods: [POST]
                  - path: /api/usuarios/login
                    methods: [POST]
        - id: sales-microservice
          uri: lb://sales-microservice     
          predicates:
              - Path=/api/sales**
          filters:
            - name: jwtAuthenticationFilter    
        - id: productors-microservice
          uri: lb://productors-microservice
          predicates:
            - Path=/api/productores/**,/api/gremios/**
          filters:
            - name: jwtAuthenticationFilter
              args:
                publicEndpoints:
                  - path: /api/productores/**
                    methods: [GET]
                  - path: /api/gremios/**
                    methods: [GET]                    
        - id: products-microservice
          uri: lb://products-microservice
          predicates:
            - Path=/api/**
          filters:
            - name: jwtAuthenticationFilter
              args:
                publicEndpoints:
                  - path: /api/productos/**
                    methods: [GET]
